# Generated by Django 4.2.4 on 2023-09-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='desription',
            new_name='description',
        ),
    ]
